# Generated by Django 4.2.5 on 2023-12-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='studentname',
        ),
    ]
