# Generated by Django 4.2.5 on 2023-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_stuname_student_studentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('studentid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('completedcredit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
