# Generated by Django 4.2.5 on 2023-12-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentuser_delete_product_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
