# Generated by Django 4.2.5 on 2023-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='cgpa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
