# Generated by Django 4.2.5 on 2023-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentuser_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='stdid',
            new_name='completedcredit',
        ),
        migrations.RenameField(
            model_name='studentuser',
            old_name='studentname',
            new_name='department',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='studentid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
