# Generated by Django 4.2.5 on 2023-12-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_stdid_studentuser_completedcredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
