# Generated by Django 4.2.5 on 2023-12-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_studentuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
