# Generated by Django 4.2.5 on 2023-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_studentuser_bio_studentuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
