# Generated by Django 4.2.5 on 2023-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_facultyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('sitelink', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('userposition', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='uploads/job.png', upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='image',
            field=models.ImageField(default='uploads/noimage.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(default='uploads/noimage.png', upload_to='uploads'),
        ),
    ]
