# Generated by Django 4.2.5 on 2023-12-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_postedjob_alter_facultyuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedjob',
            name='date',
        ),
    ]
