# Generated by Django 4.2.5 on 2023-12-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_postedjob_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
