# Generated by Django 4.2.5 on 2023-12-08 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_postedjob_date_postedjob_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
