# Generated by Django 4.2.5 on 2023-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_postedjob_date_alter_postedjob_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
