# Generated by Django 4.2.5 on 2023-12-08 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_postedjob_date_alter_postedjob_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedjob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='time',
        ),
        migrations.AddField(
            model_name='postedjob',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
