# Generated by Django 4.2.5 on 2023-12-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_postedjob_date_remove_postedjob_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='userimage',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
