# Generated by Django 4.2.5 on 2023-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_postedjob_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='image',
            field=models.ImageField(default='uploads/job.png', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='userimage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
