# Generated by Django 4.2.5 on 2023-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_postedjob_image_alter_postedjob_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
