# Generated by Django 4.2.5 on 2023-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_postedjob_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyuser',
            name='image',
            field=models.ImageField(default='uploads/noimage.png', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(default='uploads/noimage.png', null=True, upload_to='uploads'),
        ),
    ]
