# Generated by Django 4.2.5 on 2023-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_facultyuser_image_alter_studentuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyuser',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='github',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='image',
            field=models.ImageField(blank=True, default='uploads/noimage.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='linkedin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='image',
            field=models.ImageField(blank=True, default='uploads/job.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='github',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(blank=True, default='uploads/noimage.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='linkedin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
