# Generated by Django 4.2.5 on 2023-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_facultyuser_bio_alter_facultyuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='sitelink',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='userimage',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
