# Generated by Django 4.2.5 on 2023-12-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_testexcel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testexcel',
            new_name='ExcelData',
        ),
    ]
