# Generated by Django 4.2.5 on 2023-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_testexcel_exceldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('point', models.CharField(max_length=100)),
                ('trimester', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
