# Generated by Django 4.2.5 on 2023-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_recruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='deadline',
            field=models.DateField(max_length=100),
        ),
    ]
