# Generated by Django 4.2.5 on 2023-12-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_recruitment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
