# Generated by Django 4.2.5 on 2023-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_dataexcel_delete_exceldata_remove_recruitment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femail', models.CharField(max_length=100)),
                ('aid', models.IntegerField(default=0)),
                ('coursename', models.CharField(max_length=100)),
                ('courseid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('classtime', models.CharField(max_length=100)),
                ('trimester', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('did', models.IntegerField(default=0)),
            ],
        ),
    ]
