# Generated by Django 4.2.5 on 2023-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_facultyapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplication',
            name='aimage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='aname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='fimage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyapplication',
            name='femail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
