# Generated by Django 4.2.5 on 2023-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_facultyapplication_aimage_facultyapplication_aname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexcel',
            name='trimester',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
