# Generated by Django 4.2.5 on 2023-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_dataexcel_trimester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('sname', models.CharField(blank=True, max_length=100)),
                ('simage', models.CharField(blank=True, max_length=100)),
                ('sstudentid', models.CharField(max_length=100)),
                ('credit', models.CharField(blank=True, max_length=100)),
                ('aid', models.IntegerField(default=0)),
                ('aname', models.CharField(blank=True, max_length=100)),
                ('aimage', models.CharField(blank=True, max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('courseid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('classtime', models.CharField(max_length=100)),
                ('trimester', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rid', models.IntegerField(default=0)),
                ('rname', models.CharField(blank=True, max_length=100)),
                ('rimage', models.CharField(blank=True, max_length=100)),
                ('did', models.IntegerField(default=0)),
            ],
        ),
    ]
