# Generated by Django 4.2.5 on 2023-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='dimage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='dname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
