# Generated by Django 4.2.5 on 2023-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_studentapplication_dimage_studentapplication_dname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(blank=True, max_length=100)),
                ('simage', models.CharField(blank=True, max_length=100)),
                ('said', models.IntegerField()),
                ('coursename', models.CharField(max_length=100)),
                ('courseid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('trimester', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('fid', models.IntegerField()),
                ('messege', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='sid',
            field=models.IntegerField(default=0),
        ),
    ]
