# Generated by Django 4.2.5 on 2023-12-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_recommendation_alter_studentapplication_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='cgpa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
