# Generated by Django 4.2.5 on 2023-12-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_studentapplication_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='aid',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='aemail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='aimage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
