# Generated by Django 4.2.5 on 2023-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_studentapplication_aid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('simage', models.CharField(max_length=100)),
                ('said', models.IntegerField()),
                ('coursename', models.CharField(max_length=100)),
                ('courseid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('trimester', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('fid', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('fimage', models.CharField(max_length=100)),
            ],
        ),
    ]
