# Generated by Django 4.2.5 on 2023-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='fid',
        ),
        migrations.AddField(
            model_name='association',
            name='femail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
