# Generated by Django 4.2.5 on 2023-12-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_association_fid_association_femail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataExcel',
        ),
    ]
