# Generated by Django 4.2.5 on 2023-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_delete_dataexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='faid',
            field=models.IntegerField(default=0),
        ),
    ]
