# Generated by Django 4.2.5 on 2023-12-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_association_faid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='point',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
