# Generated by Django 4.2.5 on 2023-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_studentapplication_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subdate', models.CharField(max_length=100)),
                ('subcomment', models.CharField(default='', max_length=100)),
                ('subfile', models.FileField(blank=True, upload_to='uploads')),
                ('feddate', models.CharField(max_length=100)),
                ('fedcomment', models.CharField(default='', max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('postdate', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=100)),
                ('assessment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
