# Generated by Django 4.2.5 on 2023-12-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_submission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(max_length=100),
        ),
    ]
