# Generated by Django 4.2.5 on 2023-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assessment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
