# Generated by Django 4.2.5 on 2023-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_task_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fedcomment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='subcomment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction',
            field=models.TextField(),
        ),
    ]
