# Generated by Django 4.2.5 on 2023-12-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_submission_fedcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, max_length=100),
        ),
    ]
