# Generated by Django 4.2.5 on 2023-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='feddate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
