# Generated by Django 4.2.5 on 2023-12-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_studentuser_company_studentuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='alumni',
            field=models.IntegerField(default=0),
        ),
    ]
