# Generated by Django 4.2.5 on 2023-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_studentuser_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
