# Generated by Django 4.2.5 on 2023-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_message_myinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
